apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-caapi
  namespace: maurobernal
spec:
  selector:
    matchLabels:
      app: ca-caapi
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-caapi
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: container-caapi
        image: maurobernal/ca:202405141516
        imagePullPolicy: Always
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 443