# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=CfDJ8Pe0-k9jMcROihEj3fWc6kyA4QsPBKpBgwszvY87vqtQFjTfJfo6m8_xmkiS-SzwNjqYBtnQHT7Ov-ERvat_kTu6KHgxd2dPkdLXdoL8KiKk8hS8bHBTWh_lRpHyGAO9MfG-1v8EtteQklIR2cwPHdWR59_klmCrT5U1mxSvFXsfQ_svi8jAogwZlWzxj9ZJxaBRCDXkzl83ENFYS4XhFYO_PjLZ1lZ7nzQ23jla7-no1dy-EPL_ASp3Z9t8XuRGBv50ZVwsrReg1BUIf6dSxmhFq4P_7H6EPDWuSR6gCpd02Cr9c2t1XtyjI6X31bngVxPJ-8SKz3fK7NnNYttmd1SHkt08vH7gpUzSrSaIBVigCIgOby9BM-RNvIOTdVrhmDBb5AKH1RAlh7TQmbZ7ORylVz8eo6dHppnU4MqcAj9tb0blSyskpL5yF_d1JuQLc6XPiRAyff35HSCj-Yt5kVHOjRzJYnV-hwJwQm_XWxz3vCha6HcqyXkuf-CQbKi4j7gszv_F2ecr2Q7nIyCM591tmiBjxNbrcN5kwdx2qYnovGf8oMsFihXz2l5ZXEsOC_prd_huoXIoXqQyvCH_TFNO6IbQi16hd-vJLQjTelQOSr9QqZFOT5EPaZeI-gbeTIGJSGN_DgIYsD4TAjME-t1CybcyGyDXhubZiLS-JRfvUJIiFH79xoFYWLAFMMD5AT__XF9Gx8Z4Kte7nbbiar66RBJBNIFy8CeC2BUs7glT3IAFX4f_gb366O9Bx4vNtgRnGGR8HFFFu7j43BZ0hgjmWSk2ZEMsq3CUfyvUuwvYtruHY-MOeJAC6G7MRblt1g

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET TodoLists
GET {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}

###

# POST TodoLists
POST {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoListCommand
{
  "Title": "Backlog"
}

###

# PUT TodoLists
PUT {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoListCommand
{
  "Id": 1,
  "Title": "Product Backlog"
}

###

# DELETE TodoLists
DELETE {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}

###

# GET TodoItems
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/TodoItems?ListId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}

Authorization: Bearer {{BearerToken}}

###

# POST TodoItems
POST {{Web_HostAddress}}/api/TodoItems
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoItemCommand
{
  "ListId": 1,
  "Title": "Eat a burrito 🌯"
}

###

#PUT TodoItems UpdateItemDetails
PUT {{Web_HostAddress}}/api/TodoItems/UpdateItemDetails?Id=1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemDetailCommand
{
  "Id": 1,
  "ListId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT TodoItems
PUT {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemCommand
{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}

###